### ISSUE TITLE
使用网页端和API标题默认显示乱码

### ISSUE THREAD

**Issue by Don-Yin** [ygh3279799773/streamer-card#7]
![Screenshot 2024-08-15 at 08 17 58](https://github.com/user-attachments/assets/d85ecdce-2d16-4189-a366-d8f6516e0c92)

不知道是不是我本地端的问题 如果是的话打扰了
这个是最近更新后才出现的 用api不管输入什么标题 图片都是乱码 
官网进去之后看到的也是一样
https://fireflycard.shushiai.com/zh?temp=tempJin

**Comment by someone1128** [comment]
现在还会吗？

**Comment by Don-Yin** [comment]
感谢回复

现在还是存在 我尝试了移除emoji 换title 内容 安装字体 但是还都是会有乱码 temp ABC都会有

有可能是我本地的问题 我继续修复 如果找到了问题第一时间放在这 多谢了

**Comment by Don-Yin** [comment]
现在问题消失了 多谢 抱歉回复晚了
